### ISSUE TITLE
support entrypoints for plugin based command loading

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [rochacbruno/manage#14]
frameworks tend to have on structures of commands,
same goes for plugins of such frameworks

in order to support scope specific extension, it would be a great help,
to be able to specify entry points to load commands from

aka
```yaml
commands:
- entrypoint: myframework.manage_commands
- module: my_own
```
