### ISSUE TITLE
Create manage_ansible module

### ISSUE THREAD

**Issue by rochacbruno** [rochacbruno/manage#3]
### Description

Ansible as a **django_manage** core module, I think it is useful to create a **manage** module for ansible.

```yaml
tasks:
  - name: show manage debug
    manage:
        debug: options=V
  - name: Creates a naval ship
    manage:
        ship:
            new: FireStorm
```

It should rely on a MANAGE_FILE global variable
